# Netlify 配置文件
# 创建时间: 2025-10-01

[build]
  # 构建命令
  command = "cd apps/frontend && npm install && npm run build"
  # 构建输出目录
  publish = "apps/frontend/dist"
  
[build.environment]
  # Node 版本
  NODE_VERSION = "18"
  # API 地址 - 请在 Netlify 后台配置
  # VITE_API_BASE_URL = "https://your-backend-api.com/api/v1"

# SPA 路由重定向规则
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# 404 页面处理
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200

# API 代理配置（如果需要）
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-backend-api.com/api/:splat"
#   status = 200
#   force = true

