name: CI
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint backend
        run: npm run lint:backend --if-present
      
      - name: Lint frontend
        run: npm run lint:frontend --if-present
      
      - name: Test backend
        run: npm run test:backend --if-present -- --ci
      
      - name: Test frontend
        run: npm run test:frontend --if-present -- --ci
      
      - name: Build backend
        run: npm run build:backend --if-present
      
      - name: Build frontend
        run: npm run build:frontend --if-present
      
      - name: Build frontend-mobile
        run: npm run build:frontend-mobile --if-present
